### ISSUE TITLE
need a `run_bootstrap` function or drive script

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_pspec#103]
We need a function or drive script that will run the bootstrapping code on a `UVPSpec` or `container` of `UVPSpec` objects, and returns 1) fully and uniformly averaged power spectrum and 2) its bootstrapped error bars. similar to `pspec_red` for OQE

**Comment by nkern** [comment]
being addressed by #148

**Comment by philbull** [comment]
Closing as resolved.
