### ISSUE TITLE
make method for PSpecData object to apply Jy_to_mK calibration

### ISSUE THREAD

**Issue by jaguirre** [HERA-Team/hera_pspec#104]
Strictly, the visibilities in UVData should be either uncalibrated or Jy, and mK is appropriate for power spectra.  Hence, hera_pspec.pspecbeam.PSpecBeamUV.Jy_to_mK should be applied to a PSpecData object.

**Comment by nkern** [comment]
I think that's a really good point! One caveat is that `PSpecData` itself just stores the `UVData` objects in a list, so applying it to a `PSpecData` object is effectively just having it do what we had you do before, but probably this is better nonetheless.

**Comment by bhazelton** [comment]
Plus one from me. Visibilities can actually be in `mK str` as well as `uncalib` or `Jy` but I'm pretty uncomfortable with putting them in `mK`.

**Comment by nkern** [comment]
@jpober also made the following comment which I think should also be addressed with this issue:
"if you have a function that (somehow) takes Jy_to_mK, it should probably refuse to apply itself unless the pyuvdata object thinks the units are Jy"
