### ISSUE TITLE
Default cosmology settings

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_pspec#112]
Currently the default seems to be that you get a power spectrum in instrumental units if you don't by hand set a cosmology. Is that what we want?

**Comment by bhazelton** [comment]
If so, the code should at least issue a prominent warning

**Comment by nkern** [comment]
I think I may have misspoke during the design review. If you create a `PSpecBeam` object, but don't feed it a cosmology, the default behavior is that it adopts a Planck cosmology for you. If you choose to not feed that beam object into `PSpecData`, the default behavior are power spectra that are both in telescope units and are also not properly beam normalized, which in this case it issues a prominent warning. Hopefully this addresses the concerns that were raised in the design review.

**Comment by bhazelton** [comment]
That sounds good, thanks for investigating @nkern!
