### ISSUE TITLE
Polarization numbers vs. strings

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/hera_pspec#128]
I've been using a PspecBeamFromArray to make beams. There are some conflicts in polarization array key usage --- some things require polarization strings (xx, yy, etc.), while other functions reference the array index from the UVData object's polarization array.

I was able to get it working with the following changes to pspecbeam.py:
```
@@ -1476,7 +1476,7 @@ class PSpecData(object):
                 # Compute scalar to convert "telescope units" to "cosmo units"
                 if self.primary_beam is not None:
                     # using zero'th indexed poalrization as cross polarized beam are not yet implemented
-                    scalar = self.scalar(p[0], taper=taper, little_h=True)
+                    scalar = self.scalar(p_str[0], taper=taper, little_h=True)
                 else: 
                     raise_warning("Warning: self.primary_beam is not defined, "
                                   "so pspectra are not properly normalized", 
@@ -1789,7 +1789,8 @@ class PSpecData(object):
         # iterate over all pols and get conversion factors
         factors = {}
         for p in pols:
-            factors[p] = beam.Jy_to_mK(self.freqs, pol=p)
+            pol_str = uvutils.polnum2str(p)
+            factors[p] = beam.Jy_to_mK(self.freqs, pol=pol_str)
```

@nkern asked that I raise this as an issue.

**Comment by nkern** [comment]
@aelanman i think this bug was fixed with a recent PR to `hera_pspec`. Please let me know if you can reproduce this bug w/ the most up-to-date version of `hera_pspec`, and if so, can you give me the exact commands you used to recreate the bug?
thanks!

**Comment by philbull** [comment]
Closing this bug, as I think it's all fixed now.
