### ISSUE TITLE
PSpecBeamFromArray should construct pI beam from XX/YY

### ISSUE THREAD

**Issue by aelanman** [HERA-Team/hera_pspec#129]
The PSpecBeamUV class references the UVBeam class to get a pseudostokes I beam from XX/YY, but there is no similar function here.

Since Ωp is formed from integrals over the beam, and the pI beam is 0.5* (XX + YY), then:
Ωp( pI )  = 0.5* [Ωp( XX ) + Ωp( YY ) ]

For Ωpp, there's an extra cross term:
(pI)^2 = 0.25 * (XX^2 + YY^2 + 2\*XX\*YY)
So
Ωpp( pI )  = 0.25 * [Ωpp( XX ) + Ωpp( YY ) ] + 0.5 \* ʃ  XX \* YY ] dθ^2

I don't know if it's possible without the actual beams to estimate that cross term...

**Comment by nkern** [comment]
This is now something we have pushed on to the user to do themselves. Thanks for bringing it to our attention though!
