### ISSUE TITLE
Add optional error bars to UVPSpec

### ISSUE THREAD

**Issue by duncanjmr** [HERA-Team/hera_pspec#136]
When bootstrapping error bars or calculating them analytically, it might be easier if there was another variable in UVPSpec that housed an array of error bars the same size as the data_array.

Phil and I will discuss this with Adrian/Nick/company.

**Comment by anguta** [comment]
We are currently working on a "cov_array" property for the UVPspec object in "Analytic_errors" so this might be redundant.

**Comment by nkern** [comment]
being addressed by stats_array (#141) PR
