### ISSUE TITLE
`grouping.average_spectra` does not handle the `cov_array` variable

### ISSUE THREAD

**Issue by philbull** [HERA-Team/hera_pspec#147]
The `average_spectra` function does not handle the `cov_array` variable that has been added to `UVPSpec`. This causes issues when other functions discover that `cov_array` in an averaged power spectrum has a different shape to `data_array`.

`average_spectra` needs to be fixed to support `cov_array`, and unit tests and validation checks should be added to guard against issues like this.

**Comment by nkern** [comment]
Being addressed by #141 `stats_array` PR
