### ISSUE TITLE
Add code to make wedge plots

### ISSUE THREAD

**Issue by philbull** [HERA-Team/hera_pspec#154]
Add a standard function to make "wedge" plots, where multiple 1D delay spectra are plotted in order of baseline length.

**Comment by nkern** [comment]
This should be a function `hera_pspec.plot.delay_wedge()` that mirrors the structure of `hera_pspec.plot.delay_waterfall` and `hera_pspec.plot.delay_spectrum`. It should take a `UVPSpec` object and make a **single wedge plot for all blpairs in the object for each time integration**.

**Comment by philbull** [comment]
This has already been implemented as `hera_pspec.plot.delay_wedge()`.
