### ISSUE TITLE
[PSpecData] verify that n_dlys <= n_unflagged per spw

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_pspec#161]
Need a quick validation function attached to `PSpecData` to check that N_unflagged pixels per spw is greater than or equal to specified n_dlys, otherwise we run into the degree-of-freedom problem that the coarse binning was attempting to fix in the first place.

**Comment by philbull** [comment]
I'll put something together now.

**Comment by nkern** [comment]
addressed by PR #165

**Comment by philbull** [comment]
Great. Closing.
