### ISSUE TITLE
remove aipy dependence

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#184]
Aipy requires python 2 but only appears to be used for window function generation -- functionality that is easily replaced by scipy.signal, validation tests against legacy code, and by uvtools which is used to make waterfall plots. We should remove this dependence for python 3 support.

**Comment by philbull** [comment]
I agree that this should be removed eventually, so we can simplify our dependencies. But as Josh points out, it's now Py3-compatible, so this is less urgent. Closing the issue.
