### ISSUE TITLE
update md5 to use hashlib or other standard module

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/hera_pspec#187]
as per PEP memo https://www.python.org/dev/peps/pep-0004/ the md5 module is depreciated and should be replaced with hashlib. This is also required for conversion to python 3 in issue #131

**Comment by mkolopanis** [comment]
ah I'm also noticing now that the function which uses the module claims itself to be depreciated 
https://github.com/HERA-Team/hera_pspec/blob/d2de2ffd9908b76ccb79a2fc83a0caee903f0d72/hera_pspec/utils.py#L15-L20

**Comment by philbull** [comment]
I have removed this function in PR #189.
