### ISSUE TITLE
hera_pspec versioning policy

### ISSUE THREAD

**Issue by philbull** [HERA-Team/hera_pspec#192]
There's been a request to update the `hera_pspec` version more regularly. I propose the following policy:

Version number format ("semantic versioning"): `major.minor.patch`, e.g. `0.1.0`
- `major`: Incremented when there are large changes in the API or the underlying methods (e.g. if we moved away from delay spectra). Can also signify important milestones, e.g. to go from `0` -> `1`, we should be feature-complete and comprehensively validated for the delay spectrum analysis.
- `major`: Incremented when there are significant changes to functionality, including adding substantial new features or more significant bugfixes.
- `patch`: Incremented for minor/moderate-severity bugfixes and minor changes to functionality (e.g. slight changes to keyword args, adding minor new features).

The current version has been stuck at `0.1.0` for quite some time. Realistically, I think we are close to feature complete for a standard delay spectrum analysis, but there's still some way to go until we are thoroughly validated. There have also been some significant changes recently, including Py3 support, covariance-related changes, normalization, polarization-pairs... I'd like to suggest tagging a `0.8.0` release ASAP (since there's no need to wait), and a `0.9.0` release once issues #181 and #190 are merged. This signifies that we are close to `1.0.0`, while leaving plenty of room for point release if that takes longer than expected.

**Comment by bhazelton** [comment]
This proposal is not inline with semantic versioning (the three numbers with dots between is not semantic versioning). I do not advocate semantic versioning or suggest you change your plan here, but calling this semantic versioning is confusing and inaccurate.

**Comment by philbull** [comment]
Thanks @bhazelton. I'm not particularly wedded to going to 0.8.0, it was just an attempt to denote that we think we're close to a "feature-complete" release.

**Comment by bhazelton** [comment]
For reference, here is the versioning language on pyuvsim:

> We use a `generation.major.minor` format.
> 
> * Generation - Release combining multiple new physical effects and or major computational improvements.
> Testing: Backed by unittests, internal model validation, and significant external comparison.
> * Major - Adds new physical effect or major computational improvement. Small number of improvements with each release.
> Testing: Backed by unittests, internal model validation and limited external comparison.
> * Minor - Bug fixes and small improvements not expected to change physical model.
> Testing: Backed by unittests
