### ISSUE TITLE
Calculate window functions after incoherent averaging in uvpspec

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#201]
uvpspec does not appear to keep track of power-spectrum window functions through incoherent averaging. This needs to be added!

**Comment by nkern** [comment]
uvpspec doesn't hold window functions at all, but this is something we have on our wish-list..

**Comment by acliu** [comment]
I think @JianrongTan has some code that does some of this, which he is probably planning to put into a PR.

**Comment by nkern** [comment]
Addressed by #251
