### ISSUE TITLE
"Fisher^-1/2 normalization" won't decorrelate error bars

### ISSUE THREAD

**Issue by acliu** [HERA-Team/hera_pspec#21]
One option for the power spectrum normalization is to pick the "Fisher^-1/2" normalization, which has the attractive property of causing the error covariance between bandpowers to be diagonal. However, this is only true if strict/true inverse covariance weighting is used. Currently, the new OQE module does not take this into account.

**Comment by philbull** [comment]
@acliu Is this fixed by the recent decorrelation PR?

**Comment by philbull** [comment]
Adrian confirms that it's fixed.
