### ISSUE TITLE
Generalize pspec output space to not always be of length Nfreqs

### ISSUE THREAD

**Issue by acliu** [HERA-Team/hera_pspec#22]
For all implementations of the delay spectrum so far, the output vector space of the pspec pipeline must be of the same size as the input vector space. But this need not be the case, and will certainly need to be generalized as we move away from pure delay spectrum. This is not an issue to tackle in the short term (as we scramble to get basic OQE functionality up and running), but should probably be tackled in the medium term before the code gets too complicated to make generalizing this easy.

**Comment by philbull** [comment]
This is a possible student project. Tagging it as such!

**Comment by nkern** [comment]
This was addressed by coarse binning #122 PR
