### ISSUE TITLE
Adjust unit tests for test_pspecdata.py to ignore signal loss issues for now.

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#24]
Unit tests for test_get_F and test_get_q_hat and other tests that are trying to compare ideal theoretical solutions to values derived from empirical covariances  are failing because of signal loss issues that need to be thought out more carefully. 

We should adjust the existing unit tests to pass these functions for now (by allowing ~10% differences).

**Comment by philbull** [comment]
This was fixed a little while ago, but the tests are worth revisiting once we start trying to implement signal loss mitigation measures. Closing this issue for now.
