### ISSUE TITLE
Add validation tests (that are skipped) requiring a resolution of the signal loss issue

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#25]
Unit tests for test_get_F and test_get_q_hat and other tests that are trying to compare ideal theoretical solutions to values derived from empirical covariances  are failing because of signal loss issues that need to be thought out more carefully. Our proposed plan is to give these tests wide tolerances that effectively ignore the signal loss issue. 

We should write copies of these tests with stringent tolerances comparing to theoretical values without signal loss. These tests will fail until we correct for biases associate with signal loss . We should address these biases to make them pass.

**Comment by philbull** [comment]
I think this has been (or should be) superseded by the Validation effort, so closing this issue.
