### ISSUE TITLE
use pseudo inverse in get_MW when norm = H^-1? [edit: set_spw gets Ndlys kwarg]

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_pspec#256]
**[4/22/2020 edit] this was a user error. I was not setting Ndlys kwarg after setting a spectral window, so my Hv matrix was Nfreqs x Nfreqs derived from a subselection of the band, which of course results in singular matrices. I made `ds.set_spw(spw_range, ndlys=None)` take an extra kwarg `ndlys` which now if None is automatically set to the spw range, not the full frequency range. This fixes the below problems, these H matrices are totally invertible. I'll leave my (wrong) investigative work intact for posterity ;)**

I'm finding some weird things in the Mv and Wv matrices when computing them with `norm='H^-1'`.

To begin, we compute the `M` matrix with an inverse
https://github.com/HERA-Team/hera_pspec/blob/00f4d3c237b089dcb6bcc95c3958d1f0230dfa37/hera_pspec/pspecdata.py#L1686

normally, the `H` matrix is close to being real (see below for an example) with `R=I`
![Hv_mat](https://user-images.githubusercontent.com/4307358/79917696-d30cd280-83df-11ea-84f0-0a86e7d57d4b.png)

When I compute `M = inv(H)` I get the following M matrix
![Mv_invH](https://user-images.githubusercontent.com/4307358/79917755-f9cb0900-83df-11ea-955e-e20d182c54a4.png)

When I compute `M = pinv(H)` I get this following M matrix
![Mv_pinvH](https://user-images.githubusercontent.com/4307358/79917789-0c454280-83e0-11ea-9f74-9769c3e67b74.png)

which to me seems more stable. This is reinforced by the eigenspectrum of H
![H_eigenspectrum](https://user-images.githubusercontent.com/4307358/79917866-31d24c00-83e0-11ea-86c0-291c3f34c434.png)
which suggests it would benefit from a pseudoinverse.

The reason I bring this up is that it also has an impact on the resultant window function. Normally, the window function is purely real (see #255 ) in that its imaginary component is close to 0. However, in this particular case, the large imaginary values in M (with norm='H^-1') cause the imaginary component of W to be non-zero as well, which seems like an error. We could zero out the imaginary component of W, but it seems like we should probably also fix the problem with `M` when `norm='H^-1'` because the window functions also look like nonsense. Here is an example

![Wv_invH](https://user-images.githubusercontent.com/4307358/79918229-d8b6e800-83e0-11ea-8e5a-1f917febf4f9.png)
^This is the W matrix when `M = inv(H)`. Note that this W matrix, although looks nonsense, is still "properly normalized" (i.e. row-sums to unity), which is why it passed our other tests.

If we use `M = pinv(H)` instead, we get this
![Wv_pinvH](https://user-images.githubusercontent.com/4307358/79918347-11ef5800-83e1-11ea-8f80-3c735206a21a.png)

This change is going into #255 

Kudos to @JianrongTan for suggesting this test in the first place that caught this! @acliu @JianrongTan let me know if you have any comments on this.

One thing to note is that we already have a catch for singular matrices (see the line in the code below that I referenced), but because there is this low-level rumble in the H matrix I think it doesn't register as singular (even though it nearly is) and just takes the direct inverse. Is there a good reason why we just don't compute the pseudo inverse for all cases?

**Comment by acliu** [comment]
Thanks for spotting this, @nkern and @JianrongTan. Are we actually using this for the upper limits right now? I hope not. But I agree that this is something that should be fixed.

I am, however, philosophically opposed to simply slapping on a "p" to "inv" whenever there's a non-invertible matrix. We're fundamentally doing something different when taking a pseudoinverse, but people tend to forget that and if the code runs, assume that they've taken the inverse when they've taken the pseudoinverse.

I would prefer a more explicit solution. In pseudo-Cl CMB codes the bandpowers are often grouped together to allow invertibility, but I know that Aaron Parsons is philosophically opposed to this solution. How about this for a compromise? Can we have `norm='H^-1'` be something that errors out if the matrix is singular? We can add a new mode (maybe call it `norm=Hpseudoinv`) or something that we recommend to the user when the error occurs. Ideally, I'd like the new mode to implement a regularization that we put in (rather than relying on `pinv` magic). For example, I'd be fine with adding an identity matrix times epsilon (which is a small number) before the inversion. I think in certain regimes `pinv` is actually doing this, but this way it's very transparent to the user exactly what they've done to the bandpowers.

**Comment by nkern** [comment]
@acliu no I don't think we are using H^-1 for the upper limit, but I am trying to get the window functions sorted out for the upper limit, and the tests I've written are for same for all `norm` and `data_weight`  knobs and this is a failure I've spotted in doing so.

> How about this for a compromise? Can we have norm='H^-1' be something that errors out if the matrix is singular? We can add a new mode (maybe call it norm=Hpseudoinv) or something that we recommend to the user when the error occurs. Ideally, I'd like the new mode to implement a regularization that we put in (rather than relying on pinv magic).

@acliu So this is in fact exactly what the code currently does! Click on the link I made in my original post and in the few lines below you'll see what it does. The problem here (I imagine, just speculating), is that because there is this low level rumble in H that is above some threshold in `np.linalg.inv` (not accessible to the user) it doesn't actually register as singular, and takes the direct inverse. So, one possible solution is to just make the eigenspectrum plot above and manually check its effective rank and determine if we should pinv or not, and we can set this threshold a little higher to catch these cases where `np.linalg.inv` is not, and then do as you suggest, issue a warning but proceed with the `pinv`. Does that sound fair?

In terms of regularization, you should check the docstring for details on `np.linalg.pinv`. It has an `rcond=1e-15` kwarg which sets the dynamic range w.r.t. the largest eigenvalue below which it truncates eigenmodes before taking the pseudo-inverse. I think this effectively achieves the same thing as you suggest, so perhaps it's as simple as exposing this kwarg to the class method `get_MW`

**Comment by nkern** [comment]
Okay so there is a known *problem with `np.linalg.inv` that it isn't good at catching singular matrices when operating on float data types (*not clear if this is a problem with `inv` or just a fundamental problem with inverting floating point matrices). I think we should just use `np.linalg.cond` to get the condition number of `Hv` and if it is above some predefined value* (say 1e17) we use `np.linalg.pinv`. *that number was chosen to make the above problem go away--i.e. make realistic H matrices that are not invertible use `pinv`. The H matrices pictures have condition numbers of ~1e18.

**Comment by acliu** [comment]
Good! That all sounds excellent.

Does anyone have a strong preference regarding the level of the condition number at which we get worried? Based on some back-of-the-envelope thinking, I am actually worried that even without numerical noise, there could be real features that need to be inverted by `H` at the 10^20 level.

This isn't a problem for now, I think, but eventually we will need to face this. I am ok with setting this at 10^10 or 10^12 for now, and then filing an issue to remind myself to make my argument precise. Does anyone have any thoughts about this?
