### ISSUE TITLE
PYUVDATA objects with unequal time samples fail to cross multiply

### ISSUE THREAD

**Issue by jkerrigan** [HERA-Team/hera_pspec#31]
This was **not** an issue of trying to pass too many LSTs to the OQE module, but appears to be due to certain observations of PSA64 LST binned data having fewer time samples than the rest of the dataset. These reduced time sampled data would then fail in line 372 when trying to multiple the inverse transform of the R matrices.

**Comment by philbull** [comment]
Hi @jkerrigan, thanks for tracking this down. I'm not sure what we want the proper behaviour to be here -- we're always multiplying visibilities at the same LST at the moment (and assuming that the LST grids are aligned).

Is this fine for now, and we can just drop the "extra" LST bins? Or should we be doing something more sophisticated?

**Comment by nkern** [comment]
@jkerrigan can we close this issue seeing as `hera_pspec` strictly enforces each dataset to have equal Ntimes?

**Comment by jkerrigan** [comment]
Sure, sounds good.

**Comment by nkern** [comment]
addressed by #47
