### ISSUE TITLE
Make a PyPI release

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/hera_pspec#363]
PR #358 got the repo ready for a PyPI release, but no release has yet been made, and neither has a workflow been added that would make such releases automatically. It would be great to have a PyPI release of pspec for several other repos that depend on it!

**Comment by adeliegorce** [comment]
Hi, we need to make a new version release for this to happen. The last version (v0.3.0) is outdated so buggy + corresponds to the H1C IDR2 release - it would make sense to update as the IDR3 upper limits are out.

**Comment by steven-murray** [comment]
I'm not sure who has the "authority" to make a release -- @acliu, @nkern, @philbull?

**Comment by adeliegorce** [comment]
I am an admin on the repo (and you too, from what I see) so we likely can do it ourselves

**Comment by steven-murray** [comment]
ah, nice. I get confused with permissions on the hera team. Sometimes you have admin permissions to a repo but might not be considered a "core maintainer".

**Comment by adeliegorce** [comment]
This has been done: first realize on Dec 29, 2022 (https://pypi.org/project/hera-pspec/)

**Comment by adeliegorce** [comment]
This has been done: first realize on Dec 29, 2022 (https://pypi.org/project/hera-pspec/)
