### ISSUE TITLE
Routine driver scripts

### ISSUE THREAD

**Issue by acliu** [HERA-Team/hera_pspec#39]
Write scripts for the "plot avalanche" that we wish to generate every time we want to run the power spectrum pipeline.

**Comment by philbull** [comment]
This is partially addressed by the run script in PR #57.

**Comment by philbull** [comment]
Downgraded in importance because most of the ingredients now exist.

**Comment by philbull** [comment]
This is solved by Nick's recent pspec_pipe PR. Closing.
