### ISSUE TITLE
Lack of backward compatibility for non-future_array_shape in utils.uvd_to_Tsys

### ISSUE THREAD

**Issue by JianrongTan** [HERA-Team/hera_pspec#396]
In `utils.uvd_to_Tsys`, this line doesn't work if `uvd` is not using `future_array_shape`

`uvd.data_array[tinds, :, pind] *= J2K[pol]`

**Comment by adeliegorce** [comment]
Thank you for pointing this out. This issue is addressed in [PR#397](https://github.com/HERA-Team/hera_pspec/pull/397).

**Comment by adeliegorce** [comment]
@JianrongTan @lisaleemcb could you try to re-run your pipeline in the `future-array-shapes-bug` branch and let me know if this fixed your issue?

**Comment by JianrongTan** [comment]
Thanks @adeliegorce! I have tested with the updated code and the issue is solved.

**Comment by adeliegorce** [comment]
Great! Could you review the associated PR?
