### ISSUE TITLE
Incompatibilities with future pyuvdata

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_pspec#401]
We don't have a CI job set up on pyuvdata to run hera_pspec (although I'm happy to help someone set one up), so I wasn't really tracking the impact of pyuvdata developments on hera_pspec (unlike hera_cal and hera_qm). But I just grabbed the repo and it looks like a lot of tests are failing when run against the pyuvdata `prep_v3.0` branch. At a quick glance it looks like the bulk of the errors are related to a change @steven-murray made to return slices when possible from key2inds, but there also a few that seem to be related to other things.

@steven-murray fixed a set of related errors on hera_cal and hera_qm, so he may be able to help here, but I think it'd be good for someone who uses hera_pspec regularly to be tracking this.

**Comment by steven-murray** [comment]
Yup, that was part of the plan in that PR!
