### ISSUE TITLE
output from `pspec` should be complex

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_pspec#45]
right now the output from the `pspecdata.pspec` function is casted into real before it is returned. I don't think we should limit ourselves by hard-coding this into the function. we should probably return it as a complex number so the user can decide for themselves what format they want. at the very least we should provide an option to return as a complex number. the case being that casting to real eliminates some of the "noise" that should be in the imaginary part, which could be a useful diagnoistic if in fact it doesn't look noise-like.

 thoughts? @philbull

**Comment by philbull** [comment]
Yes, I agree. This should be fixed in the `boot_refactor` branch.
