### ISSUE TITLE
Required Packages in setup file

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/hera_pspec#76]
I know the README states which packages  are dependencies for this code to run properly, but it is also possible to specify required packages in the `setup.py` file. That way the package only install if dependencies are met.

This is implemented via the `'install_requires'` argument of the `setup_args` dict:

`'install_requires': ['numpy>=1.10', 'scipy>= 0.19', 'astropy>=2.0', 'etc']`

Not sure if this functionality is desired, or strictly undesired but thought I would suggest.

**Comment by nkern** [comment]
Thanks for the suggestion! I think this is a great idea, would you like to make a quick PR?

**Comment by philbull** [comment]
Fixed in PR #83.
