### ISSUE TITLE
set_cosmolog for PSpecData

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_pspec#78]
make a set_cosmology for PSpecData, make it talk to the beam appropriately, but explictly and figure out passing of cosmo info to UVPSpec

**Comment by nkern** [comment]
`UVPspec` can only have one cosmology, if it was created with a cosmology, it must keep that and only that cosmo

**Comment by nkern** [comment]
make `uvp.sensitivity` consistent with the above cosmology

**Comment by philbull** [comment]
PR #80 is approved, so I'll close this issue.
