### ISSUE TITLE
Example notebook to show users how beams work

### ISSUE THREAD

**Issue by philbull** [HERA-Team/hera_pspec#79]
Beams have been causing some confusion.

1. Should we raise a warning if a beam isn't set, to prevent people from getting output in weird units?
1. There should be an example notebook showing people how to use UV and Gaussian beams, and how to sub-class to make a custom beam.

**Comment by nkern** [comment]
Here is a start for subclassing the beam class Ridhima and I worked on:
```
class CustomBeam(hp.pspecbeam.PSpecBeamBase):
    """ custom beam object """
    def __init__(self, OmegaP, OmegaPP, beam_freqs, cosmo=None):
        self.OmegaP = OmegaP
        self.OmegaPP = OmegaPP
        self.beam_freqs = beam_freqs
        
        if cosmo is None:
            self.cosmo = hp.conversions.Cosmo_Conversions()
        
    def power_beam_int(self, stokes):
        return self.OmegaP
    
    def power_beam_sq_int(self, stokes):
        return self.OmegaPP
```

**Comment by philbull** [comment]
See PR #81 for an expanded version of this.
