### ISSUE TITLE
move legacy code to a branch, provide obvious and clear docs on how to install a branch 

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_pspec#8]
legacy code in currently in `hera_pspec/pspec.py` should probably be moved out of master and into a branch `legacy` to avoid confusion (why should the `pspec` in `hera_pspec` contain only deprecated code?). the legacy code will still be very easily accessible and "installable" via the commands
```
git fetch
git checkout legacy
python setup.py install
```
these instructions on how to install legacy PAPER code should go into the main `README.md` on the main repo to be clear and accessible to average users.

**Comment by nkern** [comment]
this should include everything in the `transiting_code` (which itself includes a copy of `pspec.py`), as well as the `tests` directory for the legacy code.

**Comment by philbull** [comment]
Now that we have successfully reproduced the simplest PAPER OQE analysis (i.e. using unit weights), I don't think there's any need to keep this code hanging around any more. It's available in other repos if someone needs to go back to it.
