### ISSUE TITLE
standard deviations for individual visiblity measurements

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#88]
We need a property of PSpecData that keeps track of the standard deviations of individual visibility measurements (real and imaginary parts) that can be used to estimate semi-analytical power-spectrum error bars. Perhaps a field dsets_stdev which contains uvdata objects whose data are the standard deviation of each measurement.

**Comment by bhazelton** [comment]
So how are you planning to calculate these? We generally need to take the statistics (i.e. stdev) along some axis, which means you don't have a separate measurement for each time/frequency/baseline. In FHD/eppsilon, for example, we take the stdev across baselines and times within an obsid, so we just have one number per frequency per obsid, which is a lot smaller than a uvdata data array would be.

**Comment by nkern** [comment]
Closing for now, as PR #117 adopted a format for dealing with this
