### ISSUE TITLE
oqe.py should contain only DataSet and create oqe_helpers.py for other miscellenious functions

### ISSUE THREAD

**Issue by anguta** [HERA-Team/hera_pspec#9]
The DataSet class in oqe.py contains most of the functions that one usually associates with an oqe while the standalone functions (such as grid_lst etc...) are more miscellaneous helper functions. I recommend changing oqe.py to only contain the DataSet class (renamed to something like OQEData? ) and moving the rest of the miscellaneous functions to a new file; oqe_helper.py

**Comment by acliu** [comment]
This is basically done, except we've called the file utils.py instead of oqe_helper.py
